# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    loader.grub = {
      device = "nodev";
      efiSupport = true;
    };
    swraid = {
      enable = true;
      mdadmConf = "MAILADDR alice
ARRAY /dev/md/fast metadata=1.2 UUID=439feb68:0aae4b2b:d4dcc20b:c7a6351e
ARRAY /dev/md/slow metadata=1.2 UUID=f64f2408:f37fe95a:1b93178f:a0b07c60";
    };
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/mapper/fast-cache";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/fast-cache";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/fast-cache";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/mnt/backups" =
    { device = "/dev/mapper/slow-vault";
      fsType = "btrfs";
      options = [ "subvol=backups" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/mapper/slow-vault";
      fsType = "btrfs";
      options = [ "subvol=media" ];
    };

  fileSystems."/mnt/photos" =
    { device = "/dev/mapper/slow-vault";
      fsType = "btrfs";
      options = [ "subvol=photos" ];
    };

  fileSystems."/mnt/data" =
    { device = "/dev/mapper/slow-vault";
      fsType = "btrfs";
      options = [ "subvol=data" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/aa1563b9-42cf-4b7a-9b4c-1e06c1f030c4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
